5 validations and exceptionhandlers
adixks/googleApi pull request #14
Opened 2023-03-15 21:02 UTC by adixks

Pls review my code.

2023-03-27 23:14 UTC, adixks commented
Pls review my code :)

2023-03-29 10:38 UTC, JaRutkowski commented
Please merge (once u'll get the 🟢 light) the #16 first and then please create the PR for this, only with the changes specific to this task.

2023-03-29 10:43 UTC, JaRutkowski requested changes
Please see the comment under PR.

2023-04-02 19:12 UTC, JaRutkowski approved these changes

2023-04-02 19:12 UTC, merged