10 setup circleci
adixks/googleApi pull request #19
Opened 2023-03-15 22:30 UTC by adixks

Pls review my code.

2023-03-25 09:55 UTC, adixks commented
Pls review my code :)

2023-03-25 12:10 UTC, adixks commented
Pls review my code :)

2023-03-29 10:35 UTC, JaRutkowski requested changes

2023-03-29 10:35 UTC, JaRutkowski commented on .circleci/config.yml
> +      - run:
Please do not use redeploy option. Please refer to the [`jfs-operations-cloud` page](https://github.com/JaRutkowski/jfs-operations-cloud/wiki/Resources-%F0%9F%93%81#circle-ci).

2023-03-29 10:36 UTC, JaRutkowski commented
Please merge (once u'll get the 🟢 light) the https://github.com/adixks/googleApi/pull/2#pullrequestreview-1362762730 first and then please create the PR for this, only with the changes specific to this task.

2023-04-02 19:19 UTC, merged